name: mlops_project  # Name of the conda environment
=======
name: arise_riders_2  # Name of the conda environment

channels:
  - conda-forge  # Community channel with most up-to-date packages

dependencies:
<<<<<<< HEAD
  - python=3.10       # Stable and widely-used Python version for compatibility
  - pandas            # Core library for data loading (CSV, Excel) and manipulation
  - numpy             # Fundamental package for numerical computing
  - openpyxl          # Excel support for pandas (read/write .xlsx files)
  - pyyaml            # Read configuration from YAML files for flexibility
  - python-dotenv     # Load environment variables from a .env file (for secrets/config)
  - pytest            # Testing framework for robust, maintainable code
  - pytest-dotenv     # Load environment variables from .env files in pytest
  - scikit-learn      # Machine learning library for model training and evaluation
  - pip               # Allows pip-only packages to be installed below

  - pip:
      - pytest-cov  # Test coverage reporting for code quality and completeness
      - black       # Code formatting to enforce style and readability
      - flake8      # Linting to check code for errors and best practices
=======
  - python=3.10  # Stable and widely-used Python version for compatibility
  - pandas       # Core library for data loading (CSV, Excel) and manipulation
  - openpyxl     # Excel support for pandas (read/write .xlsx files)
  - pyyaml       # Read configuration from YAML files for flexibility
  - python-dotenv  # Load environment variables from a .env file (for secrets/config)
  - pytest       # Testing framework for robust, maintainable code
  - pip          # Allows pip-only packages to be installed below
  - matplotlib
  - seaborn
  - scikit-learn  # Machine learning library for model training and evaluation
  - xgboost
  - plotly
  - geopy
  - pip:
      - pytest-cov  # Test coverage reporting for code quality and completeness
      - black       # Code formatting to enforce style and readability
      - flake8  
      - nbformat>=5.0