name: fraud_detection_env_dev
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - seaborn
  - matplotlib
  - plotly
  - geopy
  - pyyaml
  - jupyterlab
  - pip
  - pip:
      - bayesian-optimization
      - pytest
      - pytest-cov