name: fraud_detection_env_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - seaborn
  - matplotlib
  - plotly
  - geopy
  - pyyaml
  - jupyterlab
  - python-dotenv
  - pip
  - pip:
      - bayesian-optimization
      - pytest
      - pytest-cov
      - wandb
      - mlflow-skinny
      - hydra-core
      - omegaconf
      - pydantic==1.10.14
      - pydantic-core