# render.yaml

services:
  - type: web
    name: mlops-api
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    buildCommand: ""         # Empty because Dockerfile handles it
    startCommand: ""         # Same as above, Dockerfile CMD is used
