name: feature_engineering

channels:
  - conda-forge

dependencies:
  - python
  - pandas
  - hydra-core
  - omegaconf
  - python-dotenv
  - scikit-learn
  - pyyaml
  - geopy
  - openpyxl
  - pip
  - pip:
      - wandb