name: MLOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: fraud_detection_env_dev
          auto-activate-base: false

      - name: Install pip-only dependencies
        shell: bash -l {0}
        run: |
          pip install wandb pytest

      - name: Run all unit tests
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest tests/